package com.estudando.spring.entity;

public enum Laboratorio {
    PFIZER,
    MODERNA,
    ASTRAZENECA,
    JANSSEN,
    CORONAVAC,
    SINOPHARM,
    SPUTNIK_V,
    NOVAVAX,
    COVAXIN,
    ELI_LILLY,
    GLAXOSMITHKLINE,
    SANOFI,
    BIONTECH,
    SINOVAC,
    CUREVAC,
    INSTITUTO_BUTANTAN,
    INSTITUTO_FIOCRUZ,
    INSTITUTO_GAMALeya,
    INSTITUTO_SINOPHARM,
    INSTITUTO_SPUTNIK,
    INSTITUTO_NOVAVAX,
    INSTITUTO_COVAXIN,
    INSTITUTO_ELI_LILLY,
    MEDLEY
}
