package com.estudando.spring.entity;

public enum Via {

    ORAL,
    INJETAVEL,
    TOPICA,
    INALATORIA,
    RETAL,
    VAGINAL,
    INTRAVENOSA,
    SUBCUTANEA,
    MUSCULAR,
    SUBLINGUAL,
    TRANSDERMICA,
    OFTALMICA,
    OTICA,
    NASAL,
    INTRAUTERINA,
    INTRAMUSCULAR,
    INTRADERMICA,
    INTRAPERITONEAL,
    INTRACARDIACA,
    INTRALINFATICA,
    INTRAMEDULAR,
    INTRAVENTRICULAR,
    INTRAPERICARDICA,
    INTRAPLEURAL
}
